	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.dataTables.min.js' type='text/javascript'></script>
    <script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.dataTables.bootstrap.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/ace-extra.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/ace-elements.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/bootbox.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/chosen.jquery.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/fullcalendar.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.autosize.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.colorbox-min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery-ui.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.easypiechart.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.gritter.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.hotkeys.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.inputlimiter.1.3.1.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.knob.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.maskedinput.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.mobile.custom.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.nestable.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.slimscroll.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.sparkline.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.ui.touch-punch.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery.validate.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jquery-ui.custom.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/prettify.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/select2.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/spin.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/flot/jquery.flot.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/flot/jquery.flot.pie.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/flot/jquery.flot.resize.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/fuelux/fuelux.spinner.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/fuelux/fuelux.tree.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/fuelux/fuelux.wizard.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/fuelux/data/fuelux.tree-sample-demo-data.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jqGrid/i18n/grid.locale-en.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/jqGrid/jquery.jqGrid.min.js' type='text/javascript'></script>
	<script src='<?php echo base_url();?>assets/sass_assets/sass/theme/js/ace.min.js' type='text/javascript'></script>
	
	